import Head from 'next/head'
import { useRef } from 'react'

import Banner from './components/banner-section'
import WhyChooseUs from './components/why-choose-us-section'
import ProductSection from './components/product-section'
import Testimonials from './components/testimonials-section'
import Blog from './components/blog-section'

import styles from './../styles/homepage.module.scss'

export default function Home() {
  const formRef = useRef<null | HTMLDivElement>(null)
  const scrollToForm = () => formRef.current?.scrollIntoView({ behavior: 'smooth' })
  return (
    <>
      <Head>
        <title>Peppai Cake Shop</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main id={styles.homepage}>
        <Banner scrollToForm={scrollToForm} />
        <WhyChooseUs />
        <ProductSection />
        <Testimonials />
        <Blog />
      </main>
    </>
  )
}
