import Head from 'next/head'

import Banner from './components/banner-section'
import WhyChooseUs from './components/why-choose-us-section'
import ProductSection from './components/product-section'
import Testimonials from './components/testimonials-section'
import Blog from './components/blog-section'

import styles from './../styles/homepage.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Peppai Cake Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main id={styles.homepage}>
        <Banner />
        <WhyChooseUs />
        <ProductSection />
        <Testimonials />
        <Blog />
      </main>
    </>
  )
}
